sudo: required

language: ruby

services:
  - docker

before_install: docker build -t frontend-build .

script: docker run -it --rm -v "$TRAVIS_BUILD_DIR:/app" frontend-build

deploy:
  skip_cleanup: true
