sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull swilson96/frontend-spike

script: docker run -it --rm -v "$TRAVIS_BUILD_DIR:/app" swilson96/frontend-spike

deploy:
  skip_cleanup: true
